services:
  backupcenter-sandbox:

    container_name: backupcenter-sandbox

    build:
      context: .
      dockerfile: docker/Dockerfile

    image: backupcenter:sandbox

    ports:
      - "8087:80"

    volumes:
      - ./:/var/www/html

      - /mnt/Interno3TB/BackupsSQL:/backups

    restart: unless-stopped
