[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true
priority=10

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=20

[program:scheduler]
command=/bin/sh -c "while true; do php /var/www/html/public/scheduler.php; sleep 59; done"
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr